"""Optimization-domain constants for dataset prep and backend selection."""

from __future__ import annotations

METRIC_FALLBACK_SHARPE = -999.0
METRIC_FALLBACK_CAGR = 0.0
METRIC_FALLBACK_MAX_DRAWDOWN = 0.0
METRIC_FALLBACK_TRIPLE = (
    METRIC_FALLBACK_SHARPE,
    METRIC_FALLBACK_CAGR,
    METRIC_FALLBACK_MAX_DRAWDOWN,
)

DEFAULT_ANNUAL_PERIODS = 252

NATIVE_BACKEND_ENV = "LQ_NATIVE_BACKEND"
NATIVE_BACKEND_DLL_ENV = "LQ_NATIVE_METRICS_DLL"
NATIVE_AUTO_SELECT_ENV = "LQ_NATIVE_AUTO_SELECT"
NATIVE_MIN_SPEEDUP_ENV = "LQ_NATIVE_MIN_SPEEDUP"
NATIVE_BENCH_LOOPS_ENV = "LQ_NATIVE_BENCH_LOOPS"
NATIVE_SELECTION_TOL_ENV = "LQ_NATIVE_SELECTION_TOL"

NATIVE_MODE_AUTO = "auto"
NATIVE_MODE_NATIVE = "native"
NATIVE_MODE_NUMBA = "numba"
NATIVE_MODE_PYTHON = "python"

NATIVE_BENCH_DEFAULT_LOOPS = 256
NATIVE_BENCH_MIN_LOOPS = 32
NATIVE_BENCH_MIN_ELAPSED_SECONDS = 1e-9
NATIVE_BENCH_MIN_TOL = 1e-12
NATIVE_BENCH_DEFAULT_TOL = 1e-9
NATIVE_BENCH_RANDOM_SEED = 7
NATIVE_BENCH_SAMPLE_SIZE = 4096
NATIVE_BENCH_RETURNS_STD = 0.001
NATIVE_BENCH_STARTING_CAPITAL = 10_000.0

FROZEN_DEFAULT_SPLIT_KEY = "all"
FROZEN_DEFAULT_ROLLING_WINDOW = 32
TIMESTAMP_SMALL_THRESHOLD = 100_000_000_000
TIMESTAMP_MEDIUM_THRESHOLD = 100_000_000_000_000
TIMESTAMP_SMALL_SCALE_TO_NS = 1_000_000
TIMESTAMP_MEDIUM_SCALE_TO_NS = 1_000

MONTH_MAX_DAYS_COMMON_YEAR = (31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31)
