from dataclasses import dataclass
from typing import Optional


class Event:
    """
    Base class for all events.
    """

    pass


@dataclass(slots=True)
class MarketEvent(Event):
    """
    Handles the event of receiving a new market update (OHLCV or Tick).
    """

    time: any
    symbol: str
    open: float
    high: float
    low: float
    close: float
    volume: float
    type: str = "MARKET"


@dataclass(slots=True)
class SignalEvent(Event):
    """
    Handles the event of sending a Signal from a Strategy object.
    This is received by a Portfolio object and acted upon.
    """

    strategy_id: str
    symbol: str
    datetime: any
    signal_type: str  # 'LONG', 'SHORT', 'EXIT'
    strength: float = 1.0  # For potential position sizing
    price: Optional[float] = None  # Price at which signal was generated (optional)
    type: str = "SIGNAL"


@dataclass(slots=True)
class OrderEvent(Event):
    """
    Handles the event of sending an Order to an execution system.
    Orders are generated by the Portfolio object.
    """

    symbol: str
    order_type: str  # 'MKT', 'LMT', 'STOP', 'TRAIL_STOP'
    quantity: float
    direction: str  # 'BUY', 'SELL'
    price: Optional[float] = None
    stop_price: Optional[float] = None
    trailing_percent: Optional[float] = None
    type: str = "ORDER"


@dataclass(slots=True)
class FillEvent(Event):
    """
    Encapsulates the notion of a Filled Order, as returned
    from a brokerage. Stores the quantity of an instrument
    actually filled and at what price. In addition, stores
    the commission of the trade from the brokerage.
    """

    timeindex: any
    symbol: str
    exchange: str
    quantity: float
    direction: str
    fill_cost: Optional[float] = None
    commission: Optional[float] = None
    type: str = "FILL"
