from dataclasses import dataclass
from typing import Any


class Event:
    """Base class for all events."""

    pass


@dataclass(slots=True)
class MarketEvent(Event):
    """Handles the event of receiving a new market update (OHLCV or Tick)."""

    time: Any
    symbol: str
    open: float
    high: float
    low: float
    close: float
    volume: float
    timestamp_ns: int | None = None
    sequence: int | None = None
    type: str = "MARKET"


@dataclass(slots=True)
class MarketBatchEvent(Event):
    """Aggregated market events for one timestamp across multiple symbols."""

    time: Any
    bars: tuple[MarketEvent, ...]
    timestamp_ns: int | None = None
    sequence: int | None = None
    type: str = "MARKET_BATCH"


@dataclass(slots=True)
class SignalEvent(Event):
    """Handles the event of sending a Signal from a Strategy object.
    This is received by a Portfolio object and acted upon.
    """

    strategy_id: str
    symbol: str
    datetime: Any
    signal_type: str  # 'LONG', 'SHORT', 'EXIT'
    strength: float = 1.0  # For potential position sizing
    price: float | None = None  # Price at which signal was generated (optional)
    stop_loss: float | None = None
    take_profit: float | None = None
    position_side: str | None = None  # LONG|SHORT for futures hedge mode
    client_order_id: str | None = None
    time_in_force: str | None = None
    metadata: dict[str, Any] | None = None
    timestamp_ns: int | None = None
    sequence: int | None = None
    type: str = "SIGNAL"


@dataclass(slots=True)
class OrderEvent(Event):
    """Handles the event of sending an Order to an execution system.
    Orders are generated by the Portfolio object.
    """

    symbol: str
    order_type: str  # 'MKT', 'LMT', 'STOP', 'TRAIL_STOP'
    quantity: float
    direction: str  # 'BUY', 'SELL'
    price: float | None = None
    stop_price: float | None = None
    trailing_percent: float | None = None
    position_side: str | None = None  # LONG|SHORT for futures hedge mode
    reduce_only: bool = False
    client_order_id: str | None = None
    stop_loss: float | None = None
    take_profit: float | None = None
    time_in_force: str | None = None
    metadata: dict[str, Any] | None = None
    timestamp_ns: int | None = None
    sequence: int | None = None
    type: str = "ORDER"


@dataclass(slots=True)
class FillEvent(Event):
    """Encapsulates the notion of a Filled Order, as returned
    from a brokerage. Stores the quantity of an instrument
    actually filled and at what price. In addition, stores
    the commission of the trade from the brokerage.
    """

    timeindex: Any
    symbol: str
    exchange: str
    quantity: float
    direction: str
    fill_cost: float | None = None
    commission: float | None = None
    order_id: str | None = None
    client_order_id: str | None = None
    position_side: str | None = None
    status: str | None = None
    metadata: dict[str, Any] | None = None
    timestamp_ns: int | None = None
    sequence: int | None = None
    type: str = "FILL"
