name: Bug report
description: Report a reproducible bug in runtime, docs, or CI behavior.
title: "[bug] "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Include exact commands and files.
      placeholder: |
        1. uv sync ...
        2. uv run python ...
        3. error output ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: OS, Python, uv versions, branch/SHA.
    validations:
      required: true
